version: '3.0'

services:
    app:
        container_name: php_lesson_6_app
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        working_dir: /app
        volumes:
            - ./app:/app       
        env_file:
            ./app/.env 

    webserver:
        container_name: php_lesson_6_webserver
        build:
            context: .
            dockerfile: .docker/webserver/Dockerfile
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - '8080:80'
    
    db:
        container_name: php_lesson_6_db
        image: 'bitnami/postgresql:15.0.0'
        volumes:
            - 'db_data:/bitnami/postgresql'
        environment:
            POSTGRESQL_USERNAME: db_user
            POSTGRESQL_PASSWORD: db_pass
            POSTGRESQL_DATABASE: app

    npm:
        container_name: php_lesson_6_npm
        image: node:latest
        working_dir: /app
        volumes:
            - ./client:/app
        # command: 'npx create-react-app my-app'
        command: 'npm start'
        ports:
            - '8082:3000' 

    cron:
        container_name: php_lesson_6_cron
        build:
            context: .
            dockerfile: .docker/app/Dockerfile.cron
        working_dir: /app
        volumes:
            - ./app:/app       
        env_file:
            ./app/.env 

volumes:
    db_data:

